// http://www.convertcsv.com/csv-to-json.htm

var Players =
  {
  "AA": {
     "Name": "Worker Drone",
     "Batting": 1,
     "Running": 1,
     "Pitching": 1,
     "Fielding": 1,
     "Handedness": "R",
     "Face Type": "A",
     "TOTAL": 4,
     "Price": 5
  },
  "AB": {
     "Name": "Kimmy Eckman",
     "Batting": 6,
     "Running": 4,
     "Pitching": 3,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 16,
     "Price": 16
  },
  "AC": {
     "Name": "Maria Luna",
     "Batting": 6,
     "Running": 7,
     "Pitching": 3,
     "Fielding": 7,
     "Handedness": "L",
     "Face Type": "unique",
     "TOTAL": 23,
     "Price": 23
  },
  "AD": {
     "Name": "Angela Delvecchio",
     "Batting": 8,
     "Running": 4,
     "Pitching": 10,
     "Fielding": 1,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 23,
     "Price": 23
  },
  "AE": {
     "Name": "Vicki Kawaguchi",
     "Batting": 1,
     "Running": 9,
     "Pitching": 5,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 25,
     "Price": 25
  },
  "AF": {
     "Name": "Gretchen Hasselhoff",
     "Batting": 2,
     "Running": 8,
     "Pitching": 6,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "unique",
     "TOTAL": 20,
     "Price": 20
  },
  "AG": {
     "Name": "Sally Dobbs",
     "Batting": 7,
     "Running": 7,
     "Pitching": 7,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 28,
     "Price": 28
  },
  "AH": {
     "Name": "Billy Jean Blackwood",
     "Batting": 8,
     "Running": 6,
     "Pitching": 4,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 22,
     "Price": 22
  },
  "AI": {
     "Name": "Ashley Webber",
     "Batting": 5,
     "Running": 7,
     "Pitching": 6,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 21,
     "Price": 21
  },
  "AJ": {
     "Name": "Sidney Webber",
     "Batting": 5,
     "Running": 7,
     "Pitching": 6,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "",
     "TOTAL": 21,
     "Price": 21
  },
  "AK": {
     "Name": "Kiesha Phillips",
     "Batting": 9,
     "Running": 9,
     "Pitching": 4,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 28,
     "Price": 28
  },
  "AL": {
     "Name": "Stephanie Morgan",
     "Batting": 6,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 26,
     "Price": 26
  },
  "AM": {
     "Name": "Luanne Lui",
     "Batting": 6,
     "Running": 10,
     "Pitching": 9,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 29,
     "Price": 29
  },
  "AN": {
     "Name": "Annie Frazier",
     "Batting": 9,
     "Running": 8,
     "Pitching": 1,
     "Fielding": 6,
     "Handedness": "L",
     "Face Type": "unique",
     "TOTAL": 24,
     "Price": 24
  },
  "AO": {
     "Name": "Jocinda Smith",
     "Batting": 10,
     "Running": 5,
     "Pitching": 3,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 26,
     "Price": 26
  },
  "AP": {
     "Name": "Lisa Crocket",
     "Batting": 5,
     "Running": 8,
     "Pitching": 6,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 23,
     "Price": 23
  },
  "BA": {
     "Name": "Ronny Dobbs",
     "Batting": 7,
     "Running": 6,
     "Pitching": 7,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 23,
     "Price": 23
  },
  "BB": {
     "Name": "Achmed Khan",
     "Batting": 10,
     "Running": 7,
     "Pitching": 2,
     "Fielding": 5,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 24,
     "Price": 24
  },
  "BC": {
     "Name": "Amir Khan",
     "Batting": 7,
     "Running": 6,
     "Pitching": 9,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 26,
     "Price": 26
  },
  "BD": {
     "Name": "Kenny Kawaguchi",
     "Batting": 3,
     "Running": 8,
     "Pitching": 7,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 22,
     "Price": 22
  },
  "BE": {
     "Name": "Pete Wheeler",
     "Batting": 8,
     "Running": 10,
     "Pitching": 2,
     "Fielding": 7,
     "Handedness": "L",
     "Face Type": "unique",
     "TOTAL": 27,
     "Price": 27
  },
  "BF": {
     "Name": "Dmitri Petrovich",
     "Batting": 8,
     "Running": 7,
     "Pitching": 1,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 19,
     "Price": 19
  },
  "BG": {
     "Name": "Ricky Johnson",
     "Batting": 1,
     "Running": 8,
     "Pitching": 5,
     "Fielding": 5,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 19,
     "Price": 19
  },
  "BH": {
     "Name": "Marky Dubois",
     "Batting": 5,
     "Running": 4,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "L",
     "Face Type": "unique",
     "TOTAL": 24,
     "Price": 24
  },
  "BI": {
     "Name": "Reese Worthington",
     "Batting": 3,
     "Running": 8,
     "Pitching": 4,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 23,
     "Price": 23
  },
  "BJ": {
     "Name": "Pablo Sanchez",
     "Batting": 10,
     "Running": 9,
     "Pitching": 5,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 34,
     "Price": 34
  },
  "BK": {
     "Name": "Tony Delvecchio",
     "Batting": 7,
     "Running": 6,
     "Pitching": 3,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 23,
     "Price": 23
  },
  "BL": {
     "Name": "Jorge Garcia",
     "Batting": 8,
     "Running": 6,
     "Pitching": 4,
     "Fielding": 5,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 23,
     "Price": 23
  },
  "BM": {
     "Name": "Dante Robinson",
     "Batting": 4,
     "Running": 9,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "L",
     "Face Type": "unique",
     "TOTAL": 25,
     "Price": 25
  },
  "BN": {
     "Name": "Ernie Steele",
     "Batting": 5,
     "Running": 6,
     "Pitching": 7,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 28,
     "Price": 28
  },
  "BO": {
     "Name": "Mikey Thomas",
     "Batting": 10,
     "Running": 4,
     "Pitching": 4,
     "Fielding": 7,
     "Handedness": "L",
     "Face Type": "unique",
     "TOTAL": 25,
     "Price": 25
  },
  "BP": {
     "Name": "Mo Vaughn",
     "Batting": 8,
     "Running": 5,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "L/R",
     "Face Type": "unique",
     "TOTAL": 28,
     "Price": 28
  },
  "CA": {
     "Name": "Randy Johnson",
     "Batting": 5,
     "Running": 5,
     "Pitching": 10,
     "Fielding": 3,
     "Handedness": "R/L",
     "Face Type": "unique",
     "TOTAL": 23,
     "Price": 23
  },
  "CB": {
     "Name": "Chipper Jones",
     "Batting": 8,
     "Running": 7,
     "Pitching": 4,
     "Fielding": 8,
     "Handedness": "S/R",
     "Face Type": "unique",
     "TOTAL": 27,
     "Price": 27
  },
  "CC": {
     "Name": "Cal Ripken Jr.",
     "Batting": 8,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 30,
     "Price": 30
  },
  "CD": {
     "Name": "Nomar Garciaparra",
     "Batting": 8,
     "Running": 7,
     "Pitching": 7,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 32,
     "Price": 32
  },
  "CE": {
     "Name": "Sammy Sosa",
     "Batting": 10,
     "Running": 8,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 30,
     "Price": 30
  },
  "CF": {
     "Name": "Frank Thomas",
     "Batting": 7,
     "Running": 4,
     "Pitching": 10,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 25,
     "Price": 25
  },
  "CG": {
     "Name": "Barry Larkin",
     "Batting": 7,
     "Running": 9,
     "Pitching": 2,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 27,
     "Price": 27
  },
  "CH": {
     "Name": "Kenny Lofton",
     "Batting": 7,
     "Running": 10,
     "Pitching": 6,
     "Fielding": 8,
     "Handedness": "L",
     "Face Type": "unique",
     "TOTAL": 31,
     "Price": 31
  },
  "CI": {
     "Name": "Larry Walker",
     "Batting": 9,
     "Running": 8,
     "Pitching": 2,
     "Fielding": 9,
     "Handedness": "L/R",
     "Face Type": "unique",
     "TOTAL": 28,
     "Price": 28
  },
  "CJ": {
     "Name": "Juan Gonzalez",
     "Batting": 9,
     "Running": 7,
     "Pitching": 4,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 29,
     "Price": 29
  },
  "CK": {
     "Name": "Alex Gonzalez",
     "Batting": 5,
     "Running": 9,
     "Pitching": 3,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 23,
     "Price": 23
  },
  "CL": {
     "Name": "Jeff Bagwell",
     "Batting": 8,
     "Running": 6,
     "Pitching": 3,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 26,
     "Price": 26
  },
  "CM": {
     "Name": "Carlos Beltran",
     "Batting": 5,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 8,
     "Handedness": "S/R",
     "Face Type": "unique",
     "TOTAL": 25,
     "Price": 25
  },
  "CN": {
     "Name": "Raul Mondesi",
     "Batting": 8,
     "Running": 9,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 29,
     "Price": 29
  },
  "CO": {
     "Name": "Jeromy Burnitz",
     "Batting": 7,
     "Running": 6,
     "Pitching": 4,
     "Fielding": 7,
     "Handedness": "L/R",
     "Face Type": "unique",
     "TOTAL": 24,
     "Price": 24
  },
  "CP": {
     "Name": "Marty Cordova",
     "Batting": 6,
     "Running": 7,
     "Pitching": 7,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 24,
     "Price": 24
  },
  "DA": {
     "Name": "Vladimir Guerrero",
     "Batting": 8,
     "Running": 8,
     "Pitching": 5,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 27,
     "Price": 27
  },
  "DB": {
     "Name": "Mike Piazza",
     "Batting": 9,
     "Running": 3,
     "Pitching": 3,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 23,
     "Price": 23
  },
  "DC": {
     "Name": "Derek Jeter",
     "Batting": 8,
     "Running": 9,
     "Pitching": 3,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 30,
     "Price": 30
  },
  "DD": {
     "Name": "Jason Giambi",
     "Batting": 7,
     "Running": 4,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "L",
     "Face Type": "unique",
     "TOTAL": 26,
     "Price": 26
  },
  "DE": {
     "Name": "Curt Schilling",
     "Batting": 5,
     "Running": 6,
     "Pitching": 10,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 29,
     "Price": 29
  },
  "DF": {
     "Name": "Jason Kendall",
     "Batting": 7,
     "Running": 8,
     "Pitching": 4,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 26,
     "Price": 26
  },
  "DG": {
     "Name": "Tony Gwynn",
     "Batting": 9,
     "Running": 6,
     "Pitching": 3,
     "Fielding": 8,
     "Handedness": "L",
     "Face Type": "unique",
     "TOTAL": 26,
     "Price": 26
  },
  "DH": {
     "Name": "Barry Bonds",
     "Batting": 8,
     "Running": 10,
     "Pitching": 6,
     "Fielding": 9,
     "Handedness": "L",
     "Face Type": "unique",
     "TOTAL": 33,
     "Price": 33
  },
  "DI": {
     "Name": "Ken Griffey Jr.",
     "Batting": 9,
     "Running": 8,
     "Pitching": 5,
     "Fielding": 10,
     "Handedness": "L/R",
     "Face Type": "unique",
     "TOTAL": 32,
     "Price": 32
  },
  "DJ": {
     "Name": "Mark McGwire",
     "Batting": 10,
     "Running": 4,
     "Pitching": 6,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 27,
     "Price": 27
  },
  "DK": {
     "Name": "Jose Canseco",
     "Batting": 8,
     "Running": 8,
     "Pitching": 6,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 26,
     "Price": 26
  },
  "DL": {
     "Name": "Ivan Rodriguez",
     "Batting": 7,
     "Running": 5,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "unique",
     "TOTAL": 27,
     "Price": 27
  },
  "DM": {
     "Name": "Shawn Green",
     "Batting": 8,
     "Running": 7,
     "Pitching": 7,
     "Fielding": 5,
     "Handedness": "L/R",
     "Face Type": "unique",
     "TOTAL": 27,
     "Price": 27
  },
  "DN": {
     "Name": "Alex Rodriguez",
     "Batting": 7,
     "Running": 9,
     "Pitching": 3,
     "Fielding": 9,
     "Handedness": "L/R",
     "Face Type": "unique",
     "TOTAL": 28,
     "Price": 28
  },
  "DO": {
     "Name": "Amy Bostwick",
     "Batting": 6,
     "Running": 2,
     "Pitching": 3,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 14,
     "Price": 14
  },
  "DP": {
     "Name": "Arlene Perez",
     "Batting": 6,
     "Running": 7,
     "Pitching": 3,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 23,
     "Price": 23
  },
  "EA": {
     "Name": "Betty Houston",
     "Batting": 8,
     "Running": 4,
     "Pitching": 9,
     "Fielding": 1,
     "Handedness": "R",
     "Face Type": "J",
     "TOTAL": 22,
     "Price": 22
  },
  "EB": {
     "Name": "Cindy Chang",
     "Batting": 1,
     "Running": 9,
     "Pitching": 5,
     "Fielding": 10,
     "Handedness": "L",
     "Face Type": "K",
     "TOTAL": 25,
     "Price": 25
  },
  "EC": {
     "Name": "Clarice Reid",
     "Batting": 2,
     "Running": 8,
     "Pitching": 6,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "L",
     "TOTAL": 20,
     "Price": 20
  },
  "ED": {
     "Name": "Colleen Klinker",
     "Batting": 4,
     "Running": 5,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 24,
     "Price": 24
  },
  "EE": {
     "Name": "Debby Nagasawa",
     "Batting": 10,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 26,
     "Price": 26
  },
  "EF": {
     "Name": "Diana Hayes",
     "Batting": 5,
     "Running": 6,
     "Pitching": 7,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 21,
     "Price": 21
  },
  "EG": {
     "Name": "Esther French",
     "Batting": 5,
     "Running": 6,
     "Pitching": 7,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "J",
     "TOTAL": 21,
     "Price": 21
  },
  "EH": {
     "Name": "Francis Blewer",
     "Batting": 9,
     "Running": 9,
     "Pitching": 6,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 31,
     "Price": 31
  },
  "EI": {
     "Name": "Gail Weinmann",
     "Batting": 6,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "L",
     "Face Type": "L",
     "TOTAL": 25,
     "Price": 25
  },
  "EJ": {
     "Name": "Grace Tipton",
     "Batting": 6,
     "Running": 10,
     "Pitching": 10,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 30,
     "Price": 30
  },
  "EK": {
     "Name": "Hannah Peavy",
     "Batting": 9,
     "Running": 5,
     "Pitching": 1,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 21,
     "Price": 21
  },
  "EL": {
     "Name": "Heather Quinn",
     "Batting": 10,
     "Running": 3,
     "Pitching": 3,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 24,
     "Price": 24
  },
  "EM": {
     "Name": "Holly Franklin",
     "Batting": 5,
     "Running": 8,
     "Pitching": 6,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "J",
     "TOTAL": 23,
     "Price": 23
  },
  "EN": {
     "Name": "Isabelle Marelli",
     "Batting": 7,
     "Running": 5,
     "Pitching": 7,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 22,
     "Price": 22
  },
  "EO": {
     "Name": "Jane Davis",
     "Batting": 10,
     "Running": 9,
     "Pitching": 2,
     "Fielding": 5,
     "Handedness": "L",
     "Face Type": "L",
     "TOTAL": 26,
     "Price": 26
  },
  "EP": {
     "Name": "Joella Minotti",
     "Batting": 9,
     "Running": 5,
     "Pitching": 2,
     "Fielding": 2,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 18,
     "Price": 18
  },
  "FA": {
     "Name": "Judy Abwunza",
     "Batting": 3,
     "Running": 8,
     "Pitching": 7,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 22,
     "Price": 22
  },
  "FB": {
     "Name": "Julie Dunkel",
     "Batting": 10,
     "Running": 10,
     "Pitching": 8,
     "Fielding": 7,
     "Handedness": "L",
     "Face Type": "I",
     "TOTAL": 35,
     "Price": 35
  },
  "FC": {
     "Name": "Karen Donato",
     "Batting": 8,
     "Running": 7,
     "Pitching": 2,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "J",
     "TOTAL": 20,
     "Price": 20
  },
  "FD": {
     "Name": "Katie Shankar",
     "Batting": 1,
     "Running": 4,
     "Pitching": 5,
     "Fielding": 5,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 15,
     "Price": 15
  },
  "FE": {
     "Name": "Krissy Mulligan",
     "Batting": 5,
     "Running": 3,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "L",
     "Face Type": "L",
     "TOTAL": 23,
     "Price": 23
  },
  "FF": {
     "Name": "Lara Nunez",
     "Batting": 3,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 23,
     "Price": 23
  },
  "FG": {
     "Name": "Leah Wayne",
     "Batting": 10,
     "Running": 10,
     "Pitching": 9,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 39,
     "Price": 39
  },
  "FH": {
     "Name": "Lena Ng",
     "Batting": 7,
     "Running": 6,
     "Pitching": 3,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 23,
     "Price": 23
  },
  "FI": {
     "Name": "Linda Potter",
     "Batting": 5,
     "Running": 6,
     "Pitching": 7,
     "Fielding": 5,
     "Handedness": "R",
     "Face Type": "J",
     "TOTAL": 23,
     "Price": 23
  },
  "FJ": {
     "Name": "Liz Kinghorn",
     "Batting": 4,
     "Running": 9,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 25,
     "Price": 25
  },
  "FK": {
     "Name": "Marianna Rauf",
     "Batting": 7,
     "Running": 4,
     "Pitching": 6,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "L",
     "TOTAL": 27,
     "Price": 27
  },
  "FL": {
     "Name": "Mary Reilly",
     "Batting": 8,
     "Running": 3,
     "Pitching": 4,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 22,
     "Price": 22
  },
  "FM": {
     "Name": "Michiko Adachi",
     "Batting": 5,
     "Running": 4,
     "Pitching": 3,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 21,
     "Price": 21
  },
  "FN": {
     "Name": "Molly May",
     "Batting": 8,
     "Running": 3,
     "Pitching": 2,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 22,
     "Price": 22
  },
  "FO": {
     "Name": "Nancy Chin",
     "Batting": 5,
     "Running": 7,
     "Pitching": 8,
     "Fielding": 6,
     "Handedness": "L",
     "Face Type": "I",
     "TOTAL": 26,
     "Price": 26
  },
  "FP": {
     "Name": "Olga Tollefson",
     "Batting": 6,
     "Running": 9,
     "Pitching": 6,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "J",
     "TOTAL": 25,
     "Price": 25
  },
  "GA": {
     "Name": "Olive Haldi",
     "Batting": 6,
     "Running": 7,
     "Pitching": 2,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 22,
     "Price": 22
  },
  "GB": {
     "Name": "Petra Chekov",
     "Batting": 9,
     "Running": 4,
     "Pitching": 3,
     "Fielding": 2,
     "Handedness": "R",
     "Face Type": "L",
     "TOTAL": 18,
     "Price": 18
  },
  "GC": {
     "Name": "Ramona Bennett",
     "Batting": 7,
     "Running": 8,
     "Pitching": 8,
     "Fielding": 1,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 24,
     "Price": 24
  },
  "GD": {
     "Name": "Randi Uno",
     "Batting": 7,
     "Running": 6,
     "Pitching": 4,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 21,
     "Price": 21
  },
  "GE": {
     "Name": "Serena Damonte",
     "Batting": 4,
     "Running": 3,
     "Pitching": 7,
     "Fielding": 5,
     "Handedness": "L",
     "Face Type": "I",
     "TOTAL": 19,
     "Price": 19
  },
  "GF": {
     "Name": "Sheila Basanti",
     "Batting": 5,
     "Running": 9,
     "Pitching": 3,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "J",
     "TOTAL": 21,
     "Price": 21
  },
  "GG": {
     "Name": "Sonja Hagen",
     "Batting": 8,
     "Running": 7,
     "Pitching": 6,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 29,
     "Price": 29
  },
  "GH": {
     "Name": "Stacy Gordon",
     "Batting": 7,
     "Running": 3,
     "Pitching": 6,
     "Fielding": 3,
     "Handedness": "L",
     "Face Type": "L",
     "TOTAL": 19,
     "Price": 19
  },
  "GI": {
     "Name": "Star Moonbeam",
     "Batting": 2,
     "Running": 10,
     "Pitching": 5,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 23,
     "Price": 23
  },
  "GJ": {
     "Name": "Tanya Uchida",
     "Batting": 10,
     "Running": 7,
     "Pitching": 4,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 27,
     "Price": 27
  },
  "GK": {
     "Name": "Tiffany Bosworth",
     "Batting": 6,
     "Running": 4,
     "Pitching": 10,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 28,
     "Price": 28
  },
  "GL": {
     "Name": "Tina Herrara",
     "Batting": 3,
     "Running": 8,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "J",
     "TOTAL": 23,
     "Price": 23
  },
  "GM": {
     "Name": "Vanna Steinman",
     "Batting": 5,
     "Running": 3,
     "Pitching": 3,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 18,
     "Price": 18
  },
  "GN": {
     "Name": "Veronica Lee",
     "Batting": 7,
     "Running": 9,
     "Pitching": 3,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "L",
     "TOTAL": 26,
     "Price": 26
  },
  "GO": {
     "Name": "Whitney Singh",
     "Batting": 6,
     "Running": 9,
     "Pitching": 7,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "M",
     "TOTAL": 26,
     "Price": 26
  },
  "GP": {
     "Name": "Zena Fromme",
     "Batting": 10,
     "Running": 6,
     "Pitching": 5,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "L",
     "TOTAL": 29,
     "Price": 29
  },
  "HA": {
     "Name": "Andres Ibsen",
     "Batting": 6,
     "Running": 3,
     "Pitching": 3,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 15,
     "Price": 15
  },
  "HB": {
     "Name": "Artie Pimbleton",
     "Batting": 6,
     "Running": 7,
     "Pitching": 3,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "C",
     "TOTAL": 23,
     "Price": 23
  },
  "HC": {
     "Name": "Bobby Bulgrien",
     "Batting": 8,
     "Running": 4,
     "Pitching": 9,
     "Fielding": 1,
     "Handedness": "R",
     "Face Type": "F",
     "TOTAL": 22,
     "Price": 22
  },
  "HD": {
     "Name": "Bret Olsen",
     "Batting": 1,
     "Running": 9,
     "Pitching": 5,
     "Fielding": 10,
     "Handedness": "L",
     "Face Type": "E",
     "TOTAL": 25,
     "Price": 25
  },
  "HE": {
     "Name": "Carlos Ocampo",
     "Batting": 2,
     "Running": 8,
     "Pitching": 6,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "D",
     "TOTAL": 20,
     "Price": 20
  },
  "HF": {
     "Name": "Chad Koppel",
     "Batting": 4,
     "Running": 5,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "D",
     "TOTAL": 24,
     "Price": 24
  },
  "HG": {
     "Name": "Chico Pappas",
     "Batting": 10,
     "Running": 10,
     "Pitching": 5,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "F",
     "TOTAL": 28,
     "Price": 28
  },
  "HH": {
     "Name": "Chris Milton",
     "Batting": 5,
     "Running": 6,
     "Pitching": 7,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "C",
     "TOTAL": 21,
     "Price": 21
  },
  "HI": {
     "Name": "Chucky Flinder",
     "Batting": 5,
     "Running": 6,
     "Pitching": 7,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "D",
     "TOTAL": 21,
     "Price": 21
  },
  "HJ": {
     "Name": "Davy Marian",
     "Batting": 9,
     "Running": 9,
     "Pitching": 6,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 31,
     "Price": 31
  },
  "HK": {
     "Name": "Dominique Lowe",
     "Batting": 6,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "L",
     "Face Type": "B",
     "TOTAL": 25,
     "Price": 25
  },
  "HL": {
     "Name": "Earl Abbot",
     "Batting": 6,
     "Running": 10,
     "Pitching": 10,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "F",
     "TOTAL": 30,
     "Price": 30
  },
  "HM": {
     "Name": "Eric Lebeaux",
     "Batting": 9,
     "Running": 5,
     "Pitching": 1,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 21,
     "Price": 21
  },
  "HN": {
     "Name": "Felix Grant",
     "Batting": 10,
     "Running": 3,
     "Pitching": 3,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 24,
     "Price": 24
  },
  "HO": {
     "Name": "Fernando Diaz",
     "Batting": 5,
     "Running": 8,
     "Pitching": 6,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "D",
     "TOTAL": 23,
     "Price": 23
  },
  "HP": {
     "Name": "Franky Holly",
     "Batting": 7,
     "Running": 5,
     "Pitching": 7,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 22,
     "Price": 22
  },
  "IA": {
     "Name": "Fred Benson",
     "Batting": 10,
     "Running": 9,
     "Pitching": 2,
     "Fielding": 5,
     "Handedness": "L",
     "Face Type": "F",
     "TOTAL": 26,
     "Price": 26
  },
  "IB": {
     "Name": "Gary Allen",
     "Batting": 9,
     "Running": 5,
     "Pitching": 2,
     "Fielding": 2,
     "Handedness": "R",
     "Face Type": "G",
     "TOTAL": 18,
     "Price": 18
  },
  "IC": {
     "Name": "George Coleman",
     "Batting": 3,
     "Running": 8,
     "Pitching": 7,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 22,
     "Price": 22
  },
  "ID": {
     "Name": "Henri Deschenes",
     "Batting": 10,
     "Running": 10,
     "Pitching": 8,
     "Fielding": 7,
     "Handedness": "L",
     "Face Type": "C",
     "TOTAL": 35,
     "Price": 35
  },
  "IE": {
     "Name": "Horace Young",
     "Batting": 8,
     "Running": 7,
     "Pitching": 2,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "D",
     "TOTAL": 20,
     "Price": 20
  },
  "IF": {
     "Name": "Ibrahim Mohamed",
     "Batting": 1,
     "Running": 4,
     "Pitching": 5,
     "Fielding": 5,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 15,
     "Price": 15
  },
  "IG": {
     "Name": "Isaac Drummond",
     "Batting": 5,
     "Running": 3,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "L",
     "Face Type": "F",
     "TOTAL": 23,
     "Price": 23
  },
  "IH": {
     "Name": "Jack Joseph",
     "Batting": 3,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "G",
     "TOTAL": 23,
     "Price": 23
  },
  "II": {
     "Name": "Jay Green",
     "Batting": 10,
     "Running": 10,
     "Pitching": 9,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 39,
     "Price": 39
  },
  "IJ": {
     "Name": "Jim Kiley",
     "Batting": 7,
     "Running": 6,
     "Pitching": 3,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "C",
     "TOTAL": 23,
     "Price": 23
  },
  "IK": {
     "Name": "Johnny Omar",
     "Batting": 5,
     "Running": 6,
     "Pitching": 7,
     "Fielding": 5,
     "Handedness": "R",
     "Face Type": "D",
     "TOTAL": 23,
     "Price": 23
  },
  "IL": {
     "Name": "Jordan Thorner",
     "Batting": 4,
     "Running": 9,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 25,
     "Price": 25
  },
  "IM": {
     "Name": "Mickey O'Connor",
     "Batting": 7,
     "Running": 4,
     "Pitching": 6,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "F",
     "TOTAL": 27,
     "Price": 27
  },
  "IN": {
     "Name": "Murray Goldman",
     "Batting": 8,
     "Running": 3,
     "Pitching": 4,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "G",
     "TOTAL": 22,
     "Price": 22
  },
  "IO": {
     "Name": "Nate Kowalski",
     "Batting": 5,
     "Running": 4,
     "Pitching": 3,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 21,
     "Price": 21
  },
  "IP": {
     "Name": "Nicky Winston",
     "Batting": 8,
     "Running": 3,
     "Pitching": 2,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "C",
     "TOTAL": 22,
     "Price": 22
  },
  "JA": {
     "Name": "Omar Stephano",
     "Batting": 5,
     "Running": 7,
     "Pitching": 8,
     "Fielding": 6,
     "Handedness": "L",
     "Face Type": "D",
     "TOTAL": 26,
     "Price": 26
  },
  "JB": {
     "Name": "Paco Kaufman",
     "Batting": 6,
     "Running": 9,
     "Pitching": 6,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "D",
     "TOTAL": 25,
     "Price": 25
  },
  "JC": {
     "Name": "PJ Shareef",
     "Batting": 6,
     "Running": 7,
     "Pitching": 2,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 22,
     "Price": 22
  },
  "JD": {
     "Name": "Rafael Hendrix",
     "Batting": 9,
     "Running": 4,
     "Pitching": 3,
     "Fielding": 2,
     "Handedness": "R",
     "Face Type": "G",
     "TOTAL": 18,
     "Price": 18
  },
  "JE": {
     "Name": "Ray Tran",
     "Batting": 7,
     "Running": 8,
     "Pitching": 8,
     "Fielding": 1,
     "Handedness": "R",
     "Face Type": "C",
     "TOTAL": 24,
     "Price": 24
  },
  "JF": {
     "Name": "Robby Bocko",
     "Batting": 7,
     "Running": 6,
     "Pitching": 4,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "D",
     "TOTAL": 21,
     "Price": 21
  },
  "JG": {
     "Name": "Ryan Vanderhoek",
     "Batting": 4,
     "Running": 3,
     "Pitching": 7,
     "Fielding": 5,
     "Handedness": "L",
     "Face Type": "E",
     "TOTAL": 19,
     "Price": 19
  },
  "JH": {
     "Name": "Shane Smith",
     "Batting": 5,
     "Running": 9,
     "Pitching": 3,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "F",
     "TOTAL": 21,
     "Price": 21
  },
  "JI": {
     "Name": "Stan Olafson",
     "Batting": 8,
     "Running": 7,
     "Pitching": 6,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "G",
     "TOTAL": 29,
     "Price": 29
  },
  "JJ": {
     "Name": "Stevie Lindt",
     "Batting": 7,
     "Running": 3,
     "Pitching": 6,
     "Fielding": 3,
     "Handedness": "L",
     "Face Type": "B",
     "TOTAL": 19,
     "Price": 19
  },
  "JK": {
     "Name": "Stuart Sullivan",
     "Batting": 2,
     "Running": 10,
     "Pitching": 5,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "C",
     "TOTAL": 23,
     "Price": 23
  },
  "JL": {
     "Name": "Timmy Unger",
     "Batting": 10,
     "Running": 7,
     "Pitching": 4,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "D",
     "TOTAL": 27,
     "Price": 27
  },
  "JM": {
     "Name": "Todd Xavier",
     "Batting": 6,
     "Running": 4,
     "Pitching": 10,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 28,
     "Price": 28
  },
  "JN": {
     "Name": "Vic Soufle",
     "Batting": 3,
     "Running": 8,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "F",
     "TOTAL": 23,
     "Price": 23
  },
  "JO": {
     "Name": "Vladimir Womak",
     "Batting": 5,
     "Running": 3,
     "Pitching": 3,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "G",
     "TOTAL": 18,
     "Price": 18
  },
  "JP": {
     "Name": "Wally Evans",
     "Batting": 7,
     "Running": 9,
     "Pitching": 3,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 26,
     "Price": 26
  },
  "KA": {
     "Name": "Wing Kwan",
     "Batting": 6,
     "Running": 9,
     "Pitching": 7,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "C",
     "TOTAL": 26,
     "Price": 26
  },
  "KB": {
     "Name": "Zenon Estrada",
     "Batting": 10,
     "Running": 6,
     "Pitching": 5,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "G",
     "TOTAL": 29,
     "Price": 29
  },
  "KC": {
     "Name": "Alexis Weis",
     "Batting": 8,
     "Running": 8,
     "Pitching": 7,
     "Fielding": 2,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 25,
     "Price": 25
  },
  "KD": {
     "Name": "Angelique Harding",
     "Batting": 4,
     "Running": 3,
     "Pitching": 9,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 24,
     "Price": 24
  },
  "KE": {
     "Name": "Catherine Asher",
     "Batting": 6,
     "Running": 4,
     "Pitching": 9,
     "Fielding": 3,
     "Handedness": "L",
     "Face Type": "I",
     "TOTAL": 22,
     "Price": 22
  },
  "KF": {
     "Name": "Clair Nelson",
     "Batting": 3,
     "Running": 4,
     "Pitching": 6,
     "Fielding": 1,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 14,
     "Price": 14
  },
  "KG": {
     "Name": "Courtney Valentino",
     "Batting": 9,
     "Running": 10,
     "Pitching": 5,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 28,
     "Price": 28
  },
  "KH": {
     "Name": "Dana Sekula",
     "Batting": 3,
     "Running": 3,
     "Pitching": 4,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "H",
     "TOTAL": 14,
     "Price": 14
  },
  "KI": {
     "Name": "Ellen Martinez",
     "Batting": 7,
     "Running": 4,
     "Pitching": 3,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 20,
     "Price": 20
  },
  "KJ": {
     "Name": "Erin Harris",
     "Batting": 5,
     "Running": 6,
     "Pitching": 7,
     "Fielding": 1,
     "Handedness": "L",
     "Face Type": "M",
     "TOTAL": 19,
     "Price": 19
  },
  "KK": {
     "Name": "Esmarelda Heimann",
     "Batting": 1,
     "Running": 3,
     "Pitching": 7,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 15,
     "Price": 15
  },
  "KL": {
     "Name": "Ezra Travolta",
     "Batting": 6,
     "Running": 6,
     "Pitching": 6,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 27,
     "Price": 27
  },
  "KM": {
     "Name": "Fabienne Callahan",
     "Batting": 9,
     "Running": 1,
     "Pitching": 5,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "J",
     "TOTAL": 21,
     "Price": 21
  },
  "KN": {
     "Name": "Francesca Whitaker",
     "Batting": 8,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 27,
     "Price": 27
  },
  "KO": {
     "Name": "Gloria Keitel",
     "Batting": 5,
     "Running": 2,
     "Pitching": 5,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "L",
     "TOTAL": 21,
     "Price": 21
  },
  "KP": {
     "Name": "Heidi Thurman",
     "Batting": 1,
     "Running": 2,
     "Pitching": 1,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 8,
     "Price": 8
  },
  "LA": {
     "Name": "Joan Mae",
     "Batting": 10,
     "Running": 3,
     "Pitching": 2,
     "Fielding": 1,
     "Handedness": "L",
     "Face Type": "J",
     "TOTAL": 16,
     "Price": 16
  },
  "LB": {
     "Name": "Jody Palmer",
     "Batting": 2,
     "Running": 7,
     "Pitching": 7,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 20,
     "Price": 20
  },
  "LC": {
     "Name": "Katelyn Cain",
     "Batting": 4,
     "Running": 1,
     "Pitching": 5,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 18,
     "Price": 18
  },
  "LD": {
     "Name": "Kathy Wolf",
     "Batting": 4,
     "Running": 10,
     "Pitching": 5,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 23,
     "Price": 23
  },
  "LE": {
     "Name": "Lindsy Felgate",
     "Batting": 10,
     "Running": 10,
     "Pitching": 7,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 30,
     "Price": 30
  },
  "LF": {
     "Name": "Lorelei Ikaye",
     "Batting": 10,
     "Running": 8,
     "Pitching": 4,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "L",
     "TOTAL": 26,
     "Price": 26
  },
  "LG": {
     "Name": "Mamie Skiumsby",
     "Batting": 8,
     "Running": 4,
     "Pitching": 6,
     "Fielding": 8,
     "Handedness": "L",
     "Face Type": "M",
     "TOTAL": 26,
     "Price": 26
  },
  "LH": {
     "Name": "Mandy Coolidge",
     "Batting": 9,
     "Running": 6,
     "Pitching": 10,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 28,
     "Price": 28
  },
  "LI": {
     "Name": "Rosanna Phelps",
     "Batting": 3,
     "Running": 7,
     "Pitching": 6,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 23,
     "Price": 23
  },
  "LJ": {
     "Name": "Ruth Proutt",
     "Batting": 8,
     "Running": 9,
     "Pitching": 4,
     "Fielding": 3,
     "Handedness": "L",
     "Face Type": "I",
     "TOTAL": 24,
     "Price": 24
  },
  "LK": {
     "Name": "Samantha Winslow",
     "Batting": 7,
     "Running": 4,
     "Pitching": 3,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 22,
     "Price": 22
  },
  "LL": {
     "Name": "Tatiana Jackson",
     "Batting": 7,
     "Running": 7,
     "Pitching": 6,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "K",
     "TOTAL": 24,
     "Price": 24
  },
  "LM": {
     "Name": "Tracy Hoban",
     "Batting": 5,
     "Running": 4,
     "Pitching": 5,
     "Fielding": 9,
     "Handedness": "L",
     "Face Type": "K",
     "TOTAL": 23,
     "Price": 23
  },
  "LN": {
     "Name": "Uma Morris",
     "Batting": 7,
     "Running": 5,
     "Pitching": 7,
     "Fielding": 5,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 24,
     "Price": 24
  },
  "LO": {
     "Name": "Vanessa Goodman",
     "Batting": 5,
     "Running": 7,
     "Pitching": 4,
     "Fielding": 1,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 17,
     "Price": 17
  },
  "LP": {
     "Name": "Victoria Shamberg",
     "Batting": 2,
     "Running": 6,
     "Pitching": 3,
     "Fielding": 1,
     "Handedness": "L",
     "Face Type": "L",
     "TOTAL": 12,
     "Price": 12
  },
  "MA": {
     "Name": "Adam Van Doren",
     "Batting": 7,
     "Running": 10,
     "Pitching": 3,
     "Fielding": 3,
     "Handedness": "L",
     "Face Type": "G",
     "TOTAL": 23,
     "Price": 23
  },
  "MB": {
     "Name": "Alan Hulsman",
     "Batting": 7,
     "Running": 4,
     "Pitching": 10,
     "Fielding": 1,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 22,
     "Price": 22
  },
  "MC": {
     "Name": "Billy Mendelson",
     "Batting": 5,
     "Running": 6,
     "Pitching": 6,
     "Fielding": 1,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 18,
     "Price": 18
  },
  "MD": {
     "Name": "Brad Bender",
     "Batting": 2,
     "Running": 4,
     "Pitching": 2,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 15,
     "Price": 15
  },
  "ME": {
     "Name": "Buddy Martin",
     "Batting": 2,
     "Running": 4,
     "Pitching": 6,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 18,
     "Price": 18
  },
  "MF": {
     "Name": "Butch Sherrod",
     "Batting": 4,
     "Running": 3,
     "Pitching": 6,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "C",
     "TOTAL": 23,
     "Price": 23
  },
  "MG": {
     "Name": "Cameron Haines",
     "Batting": 1,
     "Running": 6,
     "Pitching": 4,
     "Fielding": 2,
     "Handedness": "R",
     "Face Type": "D",
     "TOTAL": 13,
     "Price": 13
  },
  "MH": {
     "Name": "Chandler Huggins",
     "Batting": 5,
     "Running": 3,
     "Pitching": 3,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 20,
     "Price": 20
  },
  "MI": {
     "Name": "Daniel Willis",
     "Batting": 5,
     "Running": 6,
     "Pitching": 2,
     "Fielding": 1,
     "Handedness": "L",
     "Face Type": "B",
     "TOTAL": 14,
     "Price": 14
  },
  "MJ": {
     "Name": "Derek McCattery",
     "Batting": 7,
     "Running": 8,
     "Pitching": 9,
     "Fielding": 2,
     "Handedness": "L",
     "Face Type": "E",
     "TOTAL": 26,
     "Price": 26
  },
  "MK": {
     "Name": "Donald Vogel",
     "Batting": 4,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "F",
     "TOTAL": 22,
     "Price": 22
  },
  "ML": {
     "Name": "Guiseppe Pachasa",
     "Batting": 8,
     "Running": 6,
     "Pitching": 4,
     "Fielding": 1,
     "Handedness": "L",
     "Face Type": "D",
     "TOTAL": 19,
     "Price": 19
  },
  "MM": {
     "Name": "Ivan King",
     "Batting": 1,
     "Running": 1,
     "Pitching": 2,
     "Fielding": 1,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 5,
     "Price": 5
  },
  "MN": {
     "Name": "Jerry Mahoney",
     "Batting": 7,
     "Running": 4,
     "Pitching": 8,
     "Fielding": 7,
     "Handedness": "L",
     "Face Type": "B",
     "TOTAL": 26,
     "Price": 26
  },
  "MO": {
     "Name": "Jose Meisenheimer",
     "Batting": 7,
     "Running": 1,
     "Pitching": 8,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 24,
     "Price": 24
  },
  "MP": {
     "Name": "Lance Lambert",
     "Batting": 9,
     "Running": 5,
     "Pitching": 7,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "C",
     "TOTAL": 27,
     "Price": 27
  },
  "NA": {
     "Name": "Marsellus Marx",
     "Batting": 10,
     "Running": 10,
     "Pitching": 6,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 32,
     "Price": 32
  },
  "NB": {
     "Name": "Matthew La Cruz",
     "Batting": 5,
     "Running": 6,
     "Pitching": 1,
     "Fielding": 2,
     "Handedness": "R",
     "Face Type": "F",
     "TOTAL": 14,
     "Price": 14
  },
  "NC": {
     "Name": "Maynard McElroy",
     "Batting": 5,
     "Running": 10,
     "Pitching": 5,
     "Fielding": 4,
     "Handedness": "L",
     "Face Type": "F",
     "TOTAL": 24,
     "Price": 24
  },
  "ND": {
     "Name": "Melvin Berger",
     "Batting": 4,
     "Running": 5,
     "Pitching": 4,
     "Fielding": 2,
     "Handedness": "R",
     "Face Type": "D",
     "TOTAL": 15,
     "Price": 15
  },
  "NE": {
     "Name": "Parker Collum",
     "Batting": 9,
     "Running": 6,
     "Pitching": 3,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 22,
     "Price": 22
  },
  "NF": {
     "Name": "Peter Levine",
     "Batting": 5,
     "Running": 2,
     "Pitching": 8,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "G",
     "TOTAL": 22,
     "Price": 22
  },
  "NG": {
     "Name": "Quentin Driver",
     "Batting": 1,
     "Running": 1,
     "Pitching": 1,
     "Fielding": 2,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 5,
     "Price": 5
  },
  "NH": {
     "Name": "Randolph Glueckert",
     "Batting": 9,
     "Running": 2,
     "Pitching": 5,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "B",
     "TOTAL": 24,
     "Price": 24
  },
  "NI": {
     "Name": "Samuel Middleton",
     "Batting": 10,
     "Running": 5,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "L",
     "Face Type": "D",
     "TOTAL": 30,
     "Price": 30
  },
  "NJ": {
     "Name": "Scotty Roth",
     "Batting": 5,
     "Running": 8,
     "Pitching": 2,
     "Fielding": 5,
     "Handedness": "R",
     "Face Type": "G",
     "TOTAL": 20,
     "Price": 20
  },
  "NK": {
     "Name": "Terry Vega",
     "Batting": 7,
     "Running": 4,
     "Pitching": 3,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "C",
     "TOTAL": 21,
     "Price": 21
  },
  "NL": {
     "Name": "Vincent Sweet",
     "Batting": 4,
     "Running": 5,
     "Pitching": 5,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "F",
     "TOTAL": 23,
     "Price": 23
  },
  "NM": {
     "Name": "Walter Hall",
     "Batting": 5,
     "Running": 2,
     "Pitching": 7,
     "Fielding": 2,
     "Handedness": "R",
     "Face Type": "F",
     "TOTAL": 16,
     "Price": 16
  },
  "NN": {
     "Name": "Wayne Pitman",
     "Batting": 3,
     "Running": 1,
     "Pitching": 4,
     "Fielding": 2,
     "Handedness": "L",
     "Face Type": "E",
     "TOTAL": 10,
     "Price": 10
  },
  "NO": {
     "Name": "Rachel La Buena",
     "Batting": 9,
     "Running": 6,
     "Pitching": 4,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 27,
     "Price": 27
  },
  "NP": {
     "Name": "Kendra Yarbrough",
     "Batting": 5,
     "Running": 2,
     "Pitching": 7,
     "Fielding": 2,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 16,
     "Price": 16
  },
  "OA": {
     "Name": "Berit Greenwalt",
     "Batting": 1,
     "Running": 1,
     "Pitching": 3,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 15,
     "Price": 15
  },
  "OB": {
     "Name": "Rose Fluegel",
     "Batting": 9,
     "Running": 2,
     "Pitching": 5,
     "Fielding": 5,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 21,
     "Price": 21
  },
  "OC": {
     "Name": "Maya Woodruff",
     "Batting": 10,
     "Running": 5,
     "Pitching": 2,
     "Fielding": 7,
     "Handedness": "L",
     "Face Type": "K",
     "TOTAL": 24,
     "Price": 24
  },
  "OD": {
     "Name": "Trent Sizemore",
     "Batting": 5,
     "Running": 8,
     "Pitching": 5,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "G",
     "TOTAL": 28,
     "Price": 28
  },
  "OE": {
     "Name": "Perry Marx",
     "Batting": 7,
     "Running": 4,
     "Pitching": 6,
     "Fielding": 3,
     "Handedness": "R",
     "Face Type": "C",
     "TOTAL": 20,
     "Price": 20
  },
  "OF": {
     "Name": "Dominic Hoskins",
     "Batting": 4,
     "Running": 5,
     "Pitching": 8,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "F",
     "TOTAL": 25,
     "Price": 25
  },
  "OG": {
     "Name": "Umberto Anders",
     "Batting": 5,
     "Running": 2,
     "Pitching": 7,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "E",
     "TOTAL": 21,
     "Price": 21
  },
  "OH": {
     "Name": "Tom Glass",
     "Batting": 5,
     "Running": 7,
     "Pitching": 8,
     "Fielding": 6,
     "Handedness": "L",
     "Face Type": "D",
     "TOTAL": 26,
     "Price": 26
  },
  "OI": {
     "Name": "Alicia Blakely",
     "Batting": 8,
     "Running": 5,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "L/R",
     "Face Type": "H",
     "TOTAL": 28,
     "Price": 28
  },
  "OJ": {
     "Name": "Amanda Hellerman",
     "Batting": 5,
     "Running": 5,
     "Pitching": 10,
     "Fielding": 3,
     "Handedness": "R/L",
     "Face Type": "I",
     "TOTAL": 23,
     "Price": 23
  },
  "OK": {
     "Name": "Anna Goudreau",
     "Batting": 8,
     "Running": 7,
     "Pitching": 4,
     "Fielding": 8,
     "Handedness": "S/R",
     "Face Type": "J",
     "TOTAL": 27,
     "Price": 27
  },
  "OL": {
     "Name": "Barbara Jones",
     "Batting": 8,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 30,
     "Price": 30
  },
  "OM": {
     "Name": "Brenda Markart",
     "Batting": 8,
     "Running": 7,
     "Pitching": 7,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "L",
     "TOTAL": 32,
     "Price": 32
  },
  "ON": {
     "Name": "Cheryl Reynolds",
     "Batting": 10,
     "Running": 8,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 30,
     "Price": 30
  },
  "OO": {
     "Name": "Christina Beattie",
     "Batting": 7,
     "Running": 4,
     "Pitching": 10,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 25,
     "Price": 25
  },
  "OP": {
     "Name": "Claudia Villarta",
     "Batting": 7,
     "Running": 9,
     "Pitching": 2,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 27,
     "Price": 27
  },
  "PA": {
     "Name": "Dawn Cozart",
     "Batting": 7,
     "Running": 10,
     "Pitching": 6,
     "Fielding": 9,
     "Handedness": "L",
     "Face Type": "J",
     "TOTAL": 32,
     "Price": 32
  },
  "PB": {
     "Name": "Emily Lewbel",
     "Batting": 9,
     "Running": 8,
     "Pitching": 4,
     "Fielding": 9,
     "Handedness": "L/R",
     "Face Type": "K",
     "TOTAL": 30,
     "Price": 30
  },
  "PC": {
     "Name": "Fay Dawson",
     "Batting": 9,
     "Running": 7,
     "Pitching": 4,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "L",
     "TOTAL": 29,
     "Price": 29
  },
  "PD": {
     "Name": "Gwen Sears",
     "Batting": 5,
     "Running": 9,
     "Pitching": 3,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 23,
     "Price": 23
  },
  "PE": {
     "Name": "Hillary Vargas",
     "Batting": 8,
     "Running": 6,
     "Pitching": 3,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 26,
     "Price": 26
  },
  "PF": {
     "Name": "Ingrid Dahlman",
     "Batting": 5,
     "Running": 7,
     "Pitching": 5,
     "Fielding": 8,
     "Handedness": "S/R",
     "Face Type": "I",
     "TOTAL": 25,
     "Price": 25
  },
  "PG": {
     "Name": "Jessica Wassersas",
     "Batting": 8,
     "Running": 9,
     "Pitching": 5,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "J",
     "TOTAL": 29,
     "Price": 29
  },
  "PH": {
     "Name": "Jillian Paine",
     "Batting": 7,
     "Running": 6,
     "Pitching": 4,
     "Fielding": 7,
     "Handedness": "L/R",
     "Face Type": "K",
     "TOTAL": 24,
     "Price": 24
  },
  "PI": {
     "Name": "Kristen Sullivan",
     "Batting": 6,
     "Running": 7,
     "Pitching": 7,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "L",
     "TOTAL": 24,
     "Price": 24
  },
  "PJ": {
     "Name": "Kay O'Toole",
     "Batting": 8,
     "Running": 8,
     "Pitching": 5,
     "Fielding": 6,
     "Handedness": "R",
     "Face Type": "M",
     "TOTAL": 27,
     "Price": 27
  },
  "PK": {
     "Name": "Libby Futterman",
     "Batting": 9,
     "Running": 3,
     "Pitching": 3,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 23,
     "Price": 23
  },
  "PL": {
     "Name": "Marilyn McDonnell",
     "Batting": 8,
     "Running": 9,
     "Pitching": 2,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 29,
     "Price": 29
  },
  "PM": {
     "Name": "Melissa Waters",
     "Batting": 7,
     "Running": 4,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "L/R",
     "Face Type": "J",
     "TOTAL": 26,
     "Price": 26
  },
  "PN": {
     "Name": "Nan Porter",
     "Batting": 5,
     "Running": 6,
     "Pitching": 10,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 29,
     "Price": 29
  },
  "PO": {
     "Name": "Pamela Kirkos",
     "Batting": 7,
     "Running": 8,
     "Pitching": 4,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "L",
     "TOTAL": 26,
     "Price": 26
  },
  "PP": {
     "Name": "Raquel Cullen",
     "Batting": 9,
     "Running": 6,
     "Pitching": 3,
     "Fielding": 8,
     "Handedness": "L",
     "Face Type": "M",
     "TOTAL": 26,
     "Price": 26
  },
  "QA": {
     "Name": "Sarah Maxwell",
     "Batting": 8,
     "Running": 10,
     "Pitching": 6,
     "Fielding": 9,
     "Handedness": "L",
     "Face Type": "H",
     "TOTAL": 33,
     "Price": 33
  },
  "QB": {
     "Name": "Susan Gore",
     "Batting": 9,
     "Running": 8,
     "Pitching": 5,
     "Fielding": 10,
     "Handedness": "R",
     "Face Type": "I",
     "TOTAL": 32,
     "Price": 32
  },
  "QC": {
     "Name": "Sophie Meyer",
     "Batting": 10,
     "Running": 4,
     "Pitching": 6,
     "Fielding": 7,
     "Handedness": "R",
     "Face Type": "J",
     "TOTAL": 27,
     "Price": 27
  },
  "QD": {
     "Name": "Tonya Lesco",
     "Batting": 8,
     "Running": 8,
     "Pitching": 6,
     "Fielding": 4,
     "Handedness": "R",
     "Face Type": "K",
     "TOTAL": 26,
     "Price": 26
  },
  "QE": {
     "Name": "Wendy Parsons",
     "Batting": 7,
     "Running": 5,
     "Pitching": 7,
     "Fielding": 8,
     "Handedness": "R",
     "Face Type": "L",
     "TOTAL": 27,
     "Price": 27
  },
  "QF": {
     "Name": "Yvonne Carter",
     "Batting": 8,
     "Running": 7,
     "Pitching": 7,
     "Fielding": 5,
     "Handedness": "L",
     "Face Type": "M",
     "TOTAL": 27,
     "Price": 27
  },
  "QG": {
     "Name": "Zoe Mallory",
     "Batting": 7,
     "Running": 9,
     "Pitching": 3,
     "Fielding": 9,
     "Handedness": "R",
     "Face Type": "H",
     "TOTAL": 28,
     "Price": 28
  },
  "QH": {
     "Name": "Mr. Clanky",
     "Batting": 8,
     "Running": 6,
     "Pitching": 10,
     "Fielding": 6,
     "Handedness": "R/L",
     "Face Type": "unique",
     "TOTAL": 30,
     "Price": 30
  },
  "QI": {
     "Name": "Custom Player",
     "Batting": 0,
     "Running": 0,
     "Pitching": 0,
     "Fielding": 0,
     "Handedness": "0",
     "Face Type": "0",
     "TOTAL": 0,
     "Price": 5
  }
}
